---
 - hosts: digital_ocean_box
   sudo: true
   remote_user: root

   vars_prompt:
    - name: "PG_PASSWORD"
      prompt: "Enter postgres password for user objective8:"
      confirm: yes

   roles:
    - common
    - postgres
    - nginx
    - ferm
    - jre
    - objective8_postgres_config
    - objective8_postgres_backups
