---
 - hosts: dob_vm

   vars:
    HOME_PATH: /home/vagrant/

   vars_prompt:
    - name: "PG_PASSWORD"
      prompt: "Enter postgres password for user objective8:"
      confirm: yes

   roles:
    - common
    - postgres
    - nginx
    - ferm
    - jre
    - objective8_postgres_config
