---
 - hosts: dob_vm
   
   vars_files:
    - "{{ CONFIG_FILE_PATH }}"

   roles:
    - common
    - postgres
    - nginx
    - ferm
    - jre
    - objective8_postgres_config
    - objective8_postgres_backups
    - objective8_application_config
